/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadRouteImport } from './routes/actividad'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as JuegoIdRouteImport } from './routes/juego.$id'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadRoute = ActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegoIdRoute = JuegoIdRouteImport.update({
  id: '/juego/$id',
  path: '/juego/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/admin': typeof AdminRoute
  '/estadisticas': typeof EstadisticasRoute
  '/juego/$id': typeof JuegoIdRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/admin': typeof AdminRoute
  '/estadisticas': typeof EstadisticasRoute
  '/juego/$id': typeof JuegoIdRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/admin': typeof AdminRoute
  '/estadisticas': typeof EstadisticasRoute
  '/juego/$id': typeof JuegoIdRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividad'
    | '/admin'
    | '/estadisticas'
    | '/juego/$id'
    | '/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividad'
    | '/admin'
    | '/estadisticas'
    | '/juego/$id'
    | '/perfil/$id'
  id:
    | '__root__'
    | '/'
    | '/actividad'
    | '/admin'
    | '/estadisticas'
    | '/juego/$id'
    | '/perfil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadRoute: typeof ActividadRoute
  AdminRoute: typeof AdminRoute
  EstadisticasRoute: typeof EstadisticasRoute
  JuegoIdRoute: typeof JuegoIdRoute
  PerfilIdRoute: typeof PerfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad': {
      id: '/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof ActividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juego/$id': {
      id: '/juego/$id'
      path: '/juego/$id'
      fullPath: '/juego/$id'
      preLoaderRoute: typeof JuegoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadRoute: ActividadRoute,
  AdminRoute: AdminRoute,
  EstadisticasRoute: EstadisticasRoute,
  JuegoIdRoute: JuegoIdRoute,
  PerfilIdRoute: PerfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
